### ISSUE TITLE
Chapter 3: Complex code descriptions too concise

### ISSUE THREAD

**Issue by mroswell** [FrontEndFoxes/workshops#44]
The explanation in the last section of Chapter 3 leaves me confused. For instance, what is ```...res```

It would be helpful throughout this chapter if each description of complex code were very detailed. For instance, rather than language like ```The forEach() method executes a provided function``` it would be helpful to have
```The forEach() method executes a provided function. The function is .... ``` In essence, link descriptions of code behavior to the specific part of the code being described.

**Comment by ratracegrad** [comment]
In the example you are referring too, they need to make multiple calls to the API. Instead of doing them one at a time, they are bundling them together and running them concurrently using the axios.all() method.  Each API call will has a response so we need a way of capturing all of the responses. We are doing that with the axios.spread() method. We are using object destructuring in this method with the ...res.

Prior to this example we provide a short description of the axios.all and axios.spread methods.

This issue can be closed.
